implemented logic to support linking stellar wallets
icon-community/xp-icon-community-backend pull request #28
Opened 2024-11-10 05:34 UTC by FidelVe

Added all the required logic to link stellar wallets in the backend

2024-11-11 13:08 UTC, R0bi7 requested changes
See comments

2024-11-11 13:08 UTC, R0bi7 commented on nestjs-rest-server/src/db/services/users-db/users-db.service.ts
> +  }
Merge linkUserEvmWallet and linkUserStellarWallet and use wallet type in switch case to do validation. No need for duplications.

2024-11-11 13:08 UTC, R0bi7 commented on nestjs-rest-server/src/user/user.controller.ts
>      } else if (linkWalletDto.type === "stellar") {
Use ChainType enum instead of hardcoding

2024-11-11 13:08 UTC, R0bi7 commented on nestjs-rest-server/src/user/user.service.ts
> +  }
Those could be merged in linkUserWallet, for distinction use ChainType enum

2024-11-11 13:08 UTC, R0bi7 commented on nestjs-rest-server/src/user/user.service.ts
> +        case "evm":
Use ChainType enum instead of hardcoding

2024-11-11 13:08 UTC, R0bi7 commented on nestjs-rest-server/src/user/user.service.ts
> +        case "stellar":
Use ChainType enum instead of hardcoding

2024-11-11 21:28 UTC, FidelVe commented on nestjs-rest-server/src/db/services/users-db/users-db.service.ts
> +  }
fixed in latest commit

2024-11-11 21:38 UTC, FidelVe commented on nestjs-rest-server/src/user/user.controller.ts
>      } else if (linkWalletDto.type === "stellar") {
fixed in latest commit

2024-11-11 21:38 UTC, FidelVe commented on nestjs-rest-server/src/user/user.service.ts
> +  }
fixed in latest commit

2024-11-11 21:38 UTC, FidelVe commented on nestjs-rest-server/src/user/user.service.ts
> +        case "evm":
fixed in latest commit

2024-11-11 21:38 UTC, FidelVe commented on nestjs-rest-server/src/user/user.service.ts
> +        case "stellar":
fixed in latest commit

2024-11-12 08:38 UTC, R0bi7 approved these changes

2024-11-12 14:23 UTC, merged